services:
  VictorMacko\AuthenticatorBundle\Security\UserProvider: ~
  VictorMacko\AuthenticatorBundle\Security\GoogleAuthenticator:
    arguments:
      $clientRegistry: '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
      $router: '@router'
      $clientName: null
      $roles: [ 'ROLE_USER', 'ROLE_OAUTH_USER' ]
      $checkRoute: 'connect_google_check'